### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AldaronLau** [ardaku/whoami#31]
If anyone wants to discuss API designs for the following (or missing) items on the roadmap, please do:

 - [x] ~No panics #29~
 - [x] Figure out API for `arch()` (Version 1.3.0) #25
 - [x] #40
 - [x] Add fallible functions (returning `io::Result`) (depends on Depends on https://github.com/ardaku/whoami/issues/30)
 - [x] https://github.com/ardaku/whoami/issues/45
 - [x] https://github.com/ardaku/whoami/issues/54 Official WASI (currently with Wasite) support
 - [ ] https://github.com/ardaku/whoami/issues/76 Official Redox support
 - [ ] Official Daku support
 - [ ] Official Android support
 - [ ] Official other platform support?

**Comment by AldaronLau** [comment]
# 1.3.0 Release Checklist
 - [x] Double-check new `arch()`/`Arch` API before committing to it for the release
 - [x] Make sure changelog covers all `arch()`/`Arch` changes
 - [x] Merge all open milestone PRs, and close all milestone issues
 - [x] Test on Fedora Linux
 - [x] Test on Ubuntu Linux (either I'll have to set this up, or someone else could do it)
 - [x] Test on WebAssembly
   - [x] Firefox
   - [x] Safari
   - [x] Chrome
   - [x] Chromium
   - [x] Gnome Web/Epiphany
   - [x] Opera (either I'll have to set this up, or someone else could do it)
   - [x] Edge
 - [x] Test on Windows
 - [x] Test on MacOS
 - [x] Test on FreeBSD (either I'll have to set this up, or someone else could do it)

**Comment by AldaronLau** [comment]
Closing in favor of https://github.com/ardaku/whoami/issues/89
